apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastdash
  labels:
    app: fastdash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastdash
  template:
    metadata:
      labels:
        app: fastdash
    spec:
      containers:
        - name: main
          image: eu.gcr.io/lustrous-baton-363720/apps/fastdash:latest
          # image: APP_IMAGE
          imagePullPolicy: IfNotPresent
          env:
          - name: MODEL_PREDICTION
            value: "http://model-inference:8080/predictions/t5/1.0"
          - name: MODEL_MANAGEMENT
            value: "http://model-inference:8081/predictions/models"
          resources:
            limits:
              cpu: "2000m"
              memory: 1Gi
            requests:
              cpu: "600m"
              memory: 64Mi
          ports:
            - containerPort: 8050
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http

---
apiVersion: v1
kind: Service
metadata:
  name: fastdash
  labels:
    app: fastdash
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: fastdash
  ports:
    - port: 8050
      name: http
      targetPort: http
