apiVersion: apps/v1
kind: Deployment
metadata:
  name: t5-inference
  labels:
    model: t5
    version: v1.0
    machine: cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      model: t5
      version: v1.0
      machine: cpu
  template:
    metadata:
      labels:
        model: t5
        version: v1.0
        machine: cpu
    spec:
      containers:
        - name: main
          image: eu.gcr.io/lustrous-baton-363720/models/t5-small:1.0-cpu
          # image: MODEL_IMAGE
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2000m"
              memory: 16Gi
            requests:
              cpu: "600m"
              memory: 2Gi
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: management
            - containerPort: 8082
              name: metrics
          args: ["torchserve", "--foreground", "--models", "all"]
          readinessProbe:
            httpGet:
              path: /models/t5
              port: management
            initialDelaySeconds: 32
            periodSeconds: 8
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 60
          livenessProbe:
            exec:
              command: ["curl", "-f", "http://localhost:8081/models/t5"]
            initialDelaySeconds: 60
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: t5-inference
  labels:
    model: t5
    version: v1.0
    machine: cpu
spec:
  type: ClusterIP
  selector:
    model: t5
    version: v1.0
    machine: cpu
  ports:
    - port: 8080
      name: http
      targetPort: http
    - port: 8081
      name: management
      targetPort: management
    - port: 8082
      name: metrics
      targetPort: metrics
