---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-gcs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: should-not-be-empty
  claimRef:
    name: airflow-dags-gcs
    namespace: airflow
  mountOptions:
    - implicit-dirs
    - uid=1001
    - gid=3003
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: PROJECT_ID-airflow-dags
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-gcs
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: airflow-dags-gcs
  storageClassName: should-not-be-empty
